const movies = [
  {
    _id: "1",
    title: "Dances with Wolves",
    image: "/images/DancesWithWolves.jpg",
    director: "Kevin Costner",
    writer: "Michael Blake",
    cast: "Kevin Costner, Mary McDowell, Graham Greene, Rodney A. Grant",
    year: "1990",
    duration: "3:01",
    media: "DVD",
    genre: "Western",
    rating: "PG-13",
    value: "5.00",
    description:
      "Sent to protect a U.S. outpost on the desolate frontier, Lt. John Dunbar (Kevin Costner) finds himself alone in the vast wilderness. Befriending the very people he's sent to protect the outpost from, the Sioux Indians, Dunbar slowly comes to revere those he once feared. But when the encroaching U.S.Army threatens to overrun the Sioux, he is forced to make a choice - one that will forever change his destiny and that of a proud and defiant nation. Winner of Seven Academy Awards Including Best Picture 1990.",
    location: "Fallston, MD",
  },
  {
    _id: "2",
    title: "Butch Cassidy and the Sundance Kid",
    image: "/images/butchcassidy.jpg",
    director: "George Roy Hill",
    writer: "William Goldman",
    cast: "Paul Newman, Robert Redford, Katherine Ross, Strother Martin",
    year: "1969",
    duration: "1:50",
    media: "DVD",
    genre: "Western",
    rating: "PG",
    value: "5.00",
    description:
      "The film won four Academy Awards: Best Cinematography; Best Original Score for a Motion Picture (not a Musical); Best Music, Song (Burt Bacharach and Hal David for &quot;Raindrops Keep Fallin' on My Head&quot;); and Best Writing, Story and Screenplay Based on Material Not Previously Published or Produced. It was nominated for Best Director, Best Picture, and Best Sound (William Edmondson and David Dockendorf).",
    location: "Fallston, MD",
  },
  {
    _id: "3",
    title: "Julie & Julia",
    image: "/images/julie&julia.jpg",
    director: "Nora Ephron",
    writer: "Nora Ephron (screenplay), Julie Powell (book)",
    cast: "Amy Adams, Meryl Streep, Stanley Tucci, Chris Messina",
    year: "2009",
    duration: "2:03",
    media: "DVD",
    genre: "Drama",
    rating: "PG-13",
    value: "5.99",
    description:
      "Julia Child's story of her start in the cooking profession is intertwined with blogger Julie Powell's 2002 challenge to cook all the recipes in Child's first book. Meryl Streep received an Academy Award nomination for Best Actresss.",
    location: "Fallston, MD",
  },
  {
    _id: "4",
    title: "Paul Blart: Mall Cop",
    image: "/images/aul_Blart_Mall_Cop.jpg",
    director: "Steve Carr",
    writer: "Kevin James, Nick Bakay",
    cast: "Kevin James, Keir O'Donnell and Jayma Mays",
    year: "2009",
    duration: "1:31",
    media: "DVD",
    genre: "Comedy",
    rating: "PG",
    value: "6.99",
    description:
      "Paul Blart is a mild-mannered, dutiful family man who works as a security guard in a New Jersey mall. For years, he has applied to become a cop, but he always fails the physical exam because he is overweight. One day, a gang of organized criminals put the mall under siege and take hostages. Blart becomes trapped inside, and because of his sense of duty, refuses to leave. He thus becomes the police department's eyes on the inside and attempts to stop the criminals on his own.",
    location: "Fallston, MD",
  },
  {
    _id: "5",
    title: "It's Complicated",
    image: "/images/ItsComplicated.jpg",
    director: "Nancy Meyers",
    writer: "Nancy Meyers",
    cast: "Meryl Streep, Alec Baldwin, Steve Martin, John Krasinski",
    year: "2009",
    duration: "2:01",
    media: "DVD",
    genre: "Comedy",
    rating: "R",
    value: "6.99",
    description:
      "Two-time Academy Award winner Meryl Streep, Steve Martin and Alec Baldwin star in this hilarious look at marriage, divorce and everything in between. Jane (Streep) has three grown kids, a thriving Santa Barbara bakery and an amicable relationship with her ex-husband, Jake (Baldwin). Now, a decade after their divorce, an innocent dinner between Jane and Jake turns into the unimaginable - an affair. Caught in the middle of their rekindled romance are Jake's young wife and Adam (MArtin), a recently divorced architect who starts to fall for Jane. Could love be sweeter the second time around? It's.......complicated!",
    location: "Fallston, MD",
  },
  {
    _id: "6",
    title: "Windtalkers",
    image: "/images/windtalkers",
    director: "John Woo",
    writer: "John Woo",
    cast: "Nicholas Cage, Adam Beach, Christian Slater",
    year: "2002",
    duration: "2:31",
    media: "DVD",
    genre: "War",
    rating: "R",
    value: "6.99",
    description:
      "Based on actual events, Windtalkers is the story of Sargeant Joe Enders (Cage) as he defends the life of Ben Yahzee (Beach), a young Navajo trained in the one wartime code never broken by the enemy.",
    location: "Fallston, MD",
  },
];

export default movies;
